# cat /etc/fluent-bit/fluent-bit.conf 
[SERVICE]
    Flush         1
    Log_Level     info
    Daemon        off

# Coleta logs do Arquivo Gerado
[INPUT]
    Name           tail
    Path	   /root/teste.log
    Tag            logs_host04

# Envio para o RK-SIEM-CORE
[OUTPUT]
    Name            opensearch
    Match           logs_host04
    Host            172.18.0.1
    Port            9200
    Index           teste-logs
    Type            _doc
    HTTP_User       admin
    HTTP_Passwd     admin
    tls             On
    tls.verify      Off
    Suppress_Type_Name   On

#[OUTPUT]
#    Name           stdout
#    Match          *
