# cat /etc/fluent-bit/fluent-bit.conf 
[SERVICE]
    Flush         1
    Log_Level     info
    Daemon        off
#    Parsers_File  parsers.conf

# Coleta logs do Apache
[INPUT]
    Name           tail
    Path	   /var/log/apache2/access.log
    Tag            apache-logs-acesso
#    Parser         apache2

# Envio para o RK-SIEM-CORE
[OUTPUT]
    Name            opensearch
    Match           apache-logs-acesso
    Host            172.20.0.1
    Port            9200
    Index           host02-logs
    Type            _doc
    HTTP_User       admin
    HTTP_Passwd     admin
    tls             On
    tls.verify      Off
    Suppress_Type_Name   On
